# ===============================================
# Raspberry Pi Toolchains(raspberry-pi-cross-compilers): This project 
# provides latest automated GCC Cross Compiler & Native (ARM & ARM64) 
# build-scripts and precompiled standalone toolchains for Raspberry Pi.


# Copyright (C) 2020 Abhishek Thakur(@abhiTronix) <abhi.una12@gmail.com>


# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# ===============================================

name: CI Builder Pi[2-3] 

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'  
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  release:
    branches:
      - master
    types: [published]
    paths-ignore:
      - '**.md'

env:
  RPI_TYPE: 2-3
  CURL_VERSION: 8.9.1
  CCACHE_COMPRESS: 1
  CCACHE_DIR: $HOME/.ccache
  USER_SFTP: ${{ secrets.USER_SFTP }}
  PASSWORD_SFTP: ${{ secrets.PASSWORD_SFTP }}

jobs:
  builder-base:
    name: Base GCC 32-bit Builder Pi[2-3]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        rpios_types: [buster, bullseye, bookworm]
        gcc_versions: [8.3.0, 10.2.1, 12.2.0]
    env:
      RPIOS_TYPE: ${{ matrix.rpios_types }}
      GCC_VERSION: ${{ matrix.gcc_versions }}
      COMPILER_TYPE: CROSS
      BASE: true
    steps:
      - uses: actions/checkout@v2
      - name: before_install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq dos2unix -y
          dos2unix build-scripts/CI/CIBB_32b 
          chmod +x build-scripts/CI/CIBB_32b 
          dos2unix patches/curl_stfp_patcher
          chmod +x patches/curl_stfp_patcher
          dos2unix utils/SF_deployer
          chmod +x utils/SF_deployer
        if: success()
      - name: install
        run: |
          sudo apt-get -y install -qq gcc g++ gperf git flex texinfo pigz gawk gfortran texinfo bison libncurses-dev ccache autoconf automake build-essential libssh2-1-dev openssl libcurl4 unzip wget figlet  libgmp-dev libmpfr-dev
          sudo /usr/sbin/update-ccache-symlinks
          echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
          source ~/.bashrc && echo $PATH
        if: success()
      - name: script
        run: bash build-scripts/CI/CIBB_32b -g $GCC_VERSION -r $RPI_TYPE -o $RPIOS_TYPE
        shell: bash
        if: success() && (github.event_name == 'pull_request' || github.event_name == 'release' || (github.event_name == 'push' && contains(github.event.head_commit.message, '[DEBUG]')))
      - name: before_script
        run: bash patches/curl_stfp_patcher
        shell: bash
        if: success() && github.event_name == 'release' && github.event.action == 'published'
      - name: deploy
        run: bash utils/SF_deployer
        shell: bash
        if: success() && github.event_name == 'release' && github.event.action == 'published'

  builder-cross:
    name: Cross GCC 32-bit Builder Pi[2-3]
    needs: builder-base
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        gcc_versions: [8.3.0, 10.2.1, 12.2.0, 13.3.0, 14.2.0]
        rpios_types: [buster, bullseye, bookworm]
    env:
      GCC_VERSION: ${{ matrix.gcc_versions }}  
      RPIOS_TYPE: ${{ matrix.rpios_types }} 
      COMPILER_TYPE: CROSS
    steps:
      - uses: actions/checkout@v2
      - name: before_install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq dos2unix -y
          dos2unix build-scripts/CI/CICTB_32b 
          chmod +x build-scripts/CI/CICTB_32b 
          dos2unix patches/curl_stfp_patcher
          chmod +x patches/curl_stfp_patcher
          dos2unix utils/SF_deployer
          chmod +x utils/SF_deployer
        if: success()
      - name: install
        run: |
          sudo apt-get -y install -qq gcc g++ gperf flex git texinfo pigz gawk gfortran texinfo bison libncurses-dev ccache autoconf automake build-essential libssh2-1-dev openssl libcurl4 unzip wget figlet  libgmp-dev libmpfr-dev
          sudo /usr/sbin/update-ccache-symlinks
          echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
          source ~/.bashrc && echo $PATH
        if: success()
      - name: script
        run: bash build-scripts/CI/CICTB_32b -g $GCC_VERSION -r $RPI_TYPE -o $RPIOS_TYPE
        shell: bash
        if: success()
      - name: before_script
        run: bash patches/curl_stfp_patcher
        shell: bash
        if: success() && github.event_name == 'release' && github.event.action == 'published'
      - name: deploy
        run: bash utils/SF_deployer
        shell: bash
        if: success() && github.event_name == 'release' && github.event.action == 'published'

  builder-native:
    name: Native GCC 32-bit Builder Pi[2-3]
    needs: [builder-base, builder-cross]
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        gcc_versions: [13.3.0, 14.2.0]
        rpios_types: [buster, bullseye, bookworm]
    env:
      GCC_VERSION: ${{ matrix.gcc_versions }}  
      RPIOS_TYPE: ${{ matrix.rpios_types }}  
      COMPILER_TYPE: NATIVE
    steps:
      - uses: actions/checkout@v2
      - name: before_install
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qq dos2unix -y
          dos2unix build-scripts/CI/CINTB_32b 
          chmod +x build-scripts/CI/CINTB_32b 
          dos2unix patches/curl_stfp_patcher
          chmod +x patches/curl_stfp_patcher
          dos2unix utils/SF_deployer
          chmod +x utils/SF_deployer
        if: success()
      - name: install
        run: |
          sudo apt-get -y install -qq gcc g++ gperf flex git texinfo pigz gawk gfortran texinfo bison libncurses-dev ccache autoconf automake build-essential libssh2-1-dev openssl libcurl4 unzip wget figlet  libgmp-dev libmpfr-dev
          sudo /usr/sbin/update-ccache-symlinks
          echo 'export PATH="/usr/lib/ccache:$PATH"' | tee -a ~/.bashrc
          source ~/.bashrc && echo $PATH
        if: success()
      - name: script
        run: bash build-scripts/CI/CINTB_32b -g $GCC_VERSION -r $RPI_TYPE -o $RPIOS_TYPE
        shell: bash
        if: success()
      - name: before_script
        run: bash patches/curl_stfp_patcher
        shell: bash
        if: success() && github.event_name == 'release' && github.event.action == 'published'
      - name: deploy
        run: bash utils/SF_deployer
        shell: bash
        if: success() && github.event_name == 'release' && github.event.action == 'published'
